/**
 * Protocol Services Index
 * 
 * Central export point for all P3 Protocol-level services.
 * These services extend cross-chain capabilities to all protocol actions.
 */

export {
  ProtocolSettlement,
  protocolSettlement,
  protocolSettlementRouter,
  type ProtocolActionType,
  type ProtocolSettlementParams,
  type ProtocolSettlementResult,
  type FeeScheduleEntry,
  type SettleMode,
  type RelayStatus,
} from './settlement';

export {
  sessionRouter,
  handshakeRouter,
  lanesRouter,
  priorityScheduler,
  PriorityScheduler,
  Priority,
  getSession,
  getAllSessions,
  updateSessionActivity,
  closeSession,
  addSSEConnection,
  removeSSEConnection,
  setSessionConnectionState,
  publishToLane,
  publishManifest,
  publishAccess,
  publishBinaryAccessFrame,
  publishSignedAccessFrame,
  broadcastBinaryAccessFrame,
  broadcastToLane,
  getConnectedClients,
  type LaneType,
  type PriorityEntry,
  type FocusSignal,
  type DeviceCapabilities,
  type SessionLanes,
  type HandshakeResponse,
  type Session,
  type SSEClient,
  type LaneEvent,
  type ManifestEvent,
  type AccessEvent,
  type ReceiptPayload,
  type BinaryAccessFrameOptions,
} from './session';

// ============================================================================
// Binary Wire Protocol (Atlas API 2.0)
// ============================================================================

export {
  AccessMode,
  Readiness,
  Action,
  type Capabilities,
  type AccessFrame,
  type ReceiptEvent,
  type AccessFrameInit,
  type ReceiptEventInit,
  buildAccessFrame,
  buildReceiptEvent,
  encodeAccessFrame,
  decodeAccessFrame,
  encodeReceiptEvent,
  decodeReceiptEvent,
  serializeAccessFrame,
  parseAccessFrame,
  serializeReceiptEvent,
  parseReceiptEvent,
  encodeBase64,
  decodeBase64,
  encodeAccessFrameForSSE,
  decodeAccessFrameFromSSE,
  encodeReceiptEventForSSE,
  decodeReceiptEventFromSSE,
  accessFrameToBase64,
  receiptEventToBase64,
  accessModeToString,
  stringToAccessMode,
  readinessToString,
  stringToReadiness,
  actionToString,
  stringToAction,
  estimateAccessFrameSize,
  estimateReceiptEventSize,
  calculateWireSize,
  formatSSEEvent,
  createAccessSSEEvent,
  createReceiptSSEEvent,
  type WireStats,
} from './wire';

export {
  signFrame,
  signAccessFrame,
  verifyFrame,
  verifyAccessFrame,
  signAndSerialize,
  parseAndVerify,
  signReceiptEvent,
  generateSigningKey,
  setSigningKey,
  clearSigningKey,
  hasSigningKey,
  rotateKey,
  pruneExpiredKeys,
  getKeyRingStatus,
  clearKeyRing,
  createSignedFrameBundle,
  type SigningResult,
  type VerificationResult,
  type SignedFrameBundle,
  type KeyRotationConfig,
} from './signing';
